POST http://localhost:5000/Games
Content-Type: application/json

{
    "password": "1",
    "email": "nkosinathi@gmail.com",
    "name": "Nkosinathi",
    "user_id": "66ecee14f0d592d9c7eab105",
    "level": "Easy",
    "score": "1",
    "gameName": "RollingBall"
}
